/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "q6.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

arraysize *
arrop_2(arraysize *argp, CLIENT *clnt)
{
	static arraysize clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, arrop,
		(xdrproc_t) xdr_arraysize, (caddr_t) argp,
		(xdrproc_t) xdr_arraysize, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
