/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q6.h"

arraysize *
arrop_2_svc(arraysize *argp, struct svc_req *rqstp)
{
	static arraysize  result;

	printf("Maximum,Minimum,Average called for an array\n");

	result.size = 3;
	static int arr[3];

	arr[0] = INT_MAX;
	arr[1] = INT_MIN;
	arr[2] = 0;

	for(int i=0;i<argp->size;i++){
		if(arr[0] > argp->arr[i]){
			arr[0] = argp->arr[i];
		}	
		if(arr[1] < argp->arr[i]){
			arr[1] = argp->arr[i];
		}
		arr[2] += argp->arr[i];
	}

	arr[2] /= argp->size;
	result.arr = arr;

	return &result;
}
