/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q8.h"

int *
substring_2_svc(strpair *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Substring check is called for two strinsgs\n");

	int l1 = argp->len1 -1;
	int l2 = argp->len2 -1;

	result = 0;
	if(l1 < l2){
		return &result;
	}
	
	char temp[l2+1];
	temp[l2]=0;
	for(int i=0;i<=l1-l2;i++){
		memcpy(temp,&argp->a[i],l2);
		result |= !strcmp(temp,argp->b);
	}
	return &result;
}
