/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q1.h"


void
palindrome_prog_1(char *host, char* str)
{
	CLIENT *clnt;
	int  *result_1;
	char * palindrome_1_arg = str;

#ifndef	DEBUG
	clnt = clnt_create (host, PALINDROME_PROG, VERSION1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = palindrome_1(&palindrome_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	if(*result_1 == 1){
		printf("Paildrome\n");
	}
	else{
		printf("Not Palindrome\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	palindrome_prog_1 (host,argv[2]);
exit (0);
}
