/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q1.h"

int *
palindrome_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Palindrome check for %s is called\n",*argp);
	result = 1;
	int len = strlen(*argp);
	for(int i=0;i<len;i++){
		if((*argp)[i] != (*argp)[len-i-1]){
			result = 0;break;
		}
	}
	return &result;
}
