/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _Q3_H_RPCGEN
#define _Q3_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct intpair {
	int a;
	int b;
};
typedef struct intpair intpair;

#define GCD_PROG 0x4562877
#define VERSION1 1

#if defined(__STDC__) || defined(__cplusplus)
#define gcd 1
extern  int * gcd_1(intpair *, CLIENT *);
extern  int * gcd_1_svc(intpair *, struct svc_req *);
extern int gcd_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define gcd 1
extern  int * gcd_1();
extern  int * gcd_1_svc();
extern int gcd_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intpair (XDR *, intpair*);

#else /* K&R C */
extern bool_t xdr_intpair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_Q3_H_RPCGEN */
