/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q3.h"


void
gcd_prog_1(char *host,int a,int b)
{
	CLIENT *clnt;
	int  *result_1;
	intpair  gcd_1_arg = {a,b};

#ifndef	DEBUG
	clnt = clnt_create (host, GCD_PROG, VERSION1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = gcd_1(&gcd_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("gcd : %d\n",*result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int a = atoi(argv[2]);
	int b = atoi(argv[3]);
	gcd_prog_1 (host,a,b);
exit (0);
}
