/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q3.h"

int gcd_s(int a,int b){
	if(a==0){
		return b;
	} 
	if(a>b){
		gcd_s(a%b,b);
	} 
	else{
		gcd_s(b%a,a);
	} 
}

int *
gcd_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("GCD for %d and %d is called\n",argp->a,argp->b);

	result = gcd_s(argp->a,argp->b);

	return &result;
}
