/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _Q2_H_RPCGEN
#define _Q2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define LEAPYEAR_PROG 0x4562877
#define VERSION1 1

#if defined(__STDC__) || defined(__cplusplus)
#define leapyear 1
extern  int * leapyear_1(int *, CLIENT *);
extern  int * leapyear_1_svc(int *, struct svc_req *);
extern int leapyear_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define leapyear 1
extern  int * leapyear_1();
extern  int * leapyear_1_svc();
extern int leapyear_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_Q2_H_RPCGEN */
