/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q2.h"


void
leapyear_prog_1(char *host,int year)
{
	CLIENT *clnt;
	int  *result_1;
	int  leapyear_1_arg = year;

#ifndef	DEBUG
	clnt = clnt_create (host, LEAPYEAR_PROG, VERSION1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = leapyear_1(&leapyear_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	if(*result_1 == 1){
		printf("Leap Year\n");
	}else{
		printf("Not Leap Year\n");
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int year = atoi(argv[2]);
	leapyear_prog_1 (host,year);
exit (0);
}
