/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q2.h"

int *
leapyear_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Leap year check for %d is called\n",*argp);
	result = 0;

	if(*argp % 4 == 0){
		result = 1;
	}
	if(*argp % 100 == 0){
		result = 0;
	}

	if(*argp % 400 == 0){
		result = 1; 
	}
	return &result;
}
