/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q5.h"

intpair *
swap_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static intpair  result;

	/*
	 * insert server code here
	 */
	printf("Swap called\n");
	result.a = argp->b;
	result.b = argp->a;
	return &result;
}
