/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REV_H_RPCGEN
#define _REV_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define REVERSE_PROG 0x12349999
#define VERSION1 1

#if defined(__STDC__) || defined(__cplusplus)
#define reverse 1
extern  int * reverse_1(int *, CLIENT *);
extern  int * reverse_1_svc(int *, struct svc_req *);
extern int reverse_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define reverse 1
extern  int * reverse_1();
extern  int * reverse_1_svc();
extern int reverse_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REV_H_RPCGEN */
