/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rev.h"

void reverse_prog_1(char *host, int nm)
{
	CLIENT *clnt;
	int *result_1;
	int reverse_1_arg = nm;

#ifndef DEBUG
	clnt = clnt_create(host, REVERSE_PROG, VERSION1, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	result_1 = reverse_1(&reverse_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Result : %d", *result_1);
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 3)
	{
		printf("usage: %s server_host NUMBER\n", argv[0]);
		exit(1);
	}
	
	host = argv[1];
	int nm = atoi(argv[2]);

	reverse_prog_1(host, nm);
	exit(0);
}
