/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rev.h"

int my_rev(int x)
{
	int ans = 0;
	int r;
	while (x != 0)
	{
		r = x % 10;
		ans += r;
		int k = x;
		k /= 10;
		if (k)
			ans *= 10;
		x /= 10;
	}
	return ans;
}

int *reverse_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;
	printf("Reverse for %d is called\n", *argp);
	
	int x = *argp;
	result = my_rev(x);

	return &result;
}
