/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q7.h"

int *
cmp_2_svc(strpair *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Compare called for two strings\n");
	result = strcmp(argp->a,argp->b);
	return &result;
}
