/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _Q9_H_RPCGEN
#define _Q9_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct strpair {
	int len1;
	char *a;
	int len2;
	char *b;
};
typedef struct strpair strpair;

#define CONCAT_PROG 0x20000009
#define VERSION1 1

#if defined(__STDC__) || defined(__cplusplus)
#define concatenate 1
extern  char ** concatenate_1(strpair *, CLIENT *);
extern  char ** concatenate_1_svc(strpair *, struct svc_req *);
extern int concat_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define concatenate 1
extern  char ** concatenate_1();
extern  char ** concatenate_1_svc();
extern int concat_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_strpair (XDR *, strpair*);

#else /* K&R C */
extern bool_t xdr_strpair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_Q9_H_RPCGEN */
