/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q9.h"


void
concat_prog_1(char *host,char* a,char* b)
{
	CLIENT *clnt;
	char * *result_1;
	strpair  concatenate_1_arg = {strlen(a)+1,a,strlen(b)+1,b};

#ifndef	DEBUG
	clnt = clnt_create (host, CONCAT_PROG, VERSION1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = concatenate_1(&concatenate_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("%s\n",*result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	concat_prog_1 (host,argv[2],argv[3]);
exit (0);
}
