/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q9.h"

char **
concatenate_1_svc(strpair *argp, struct svc_req *rqstp)
{
	static char * result;
	printf("Concatenation of two strings is called. \n");
	result = malloc(argp->len1 + argp->len2 +1);
	memcpy(result,argp->a,argp->len1);
	strcat(result,argp->b);
	return &result;
}
