/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _Q4_H_RPCGEN
#define _Q4_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SQRT_PROG 0x4562877
#define VERSION1 1

#if defined(__STDC__) || defined(__cplusplus)
#define sqrt 1
extern  float * sqrt_1(float *, CLIENT *);
extern  float * sqrt_1_svc(float *, struct svc_req *);
extern int sqrt_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sqrt 1
extern  float * sqrt_1();
extern  float * sqrt_1_svc();
extern int sqrt_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_Q4_H_RPCGEN */
