/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q4.h"


void
sqrt_prog_1(char *host,float n)
{
	CLIENT *clnt;
	float  *result_1;
	float  sqrt_1_arg=n;

#ifndef	DEBUG
	clnt = clnt_create (host, SQRT_PROG, VERSION1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sqrt_1(&sqrt_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("sqrt : %f\n",*result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	float n = atof(argv[2]);
	sqrt_prog_1 (host,n);
exit (0);
}
