/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "maxArray.h"

int *maxarray_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int result;

	/*
	 * insert server code here
	 */
	printf("The maximum of the array : (");
	for (int i = 0; i < argp->size; i++)
	{
		printf("%d ", argp->array[i]);
	}
	printf(") is required\n");
	int n = argp->size;
	int *arr = argp->array;
	int max = arr[0];
	for (int i = 1; i < n; i++)
	{
		if (arr[i] > max)
		{
			max = arr[i];
		}
	}
	result = max;

	return &result;
}
