/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "maxArray.h"

void maxarray_prog_1(char *host)
{
	CLIENT *clnt;
	int *result_1;
	numbers maxarray_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, maxArray_PROG, maxArray_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */
	printf("Enter the number of elements in the array : ");
	scanf("%d", &maxarray_1_arg.size);
	printf("Enter the elements of the array : \n");
	for (int i = 0; i < maxarray_1_arg.size; i++)
	{
		scanf("%d", &maxarray_1_arg.array[i]);
	}
	result_1 = maxarray_1(&maxarray_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("The maximum element in the array is : %d\n", *result_1);
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	maxarray_prog_1(host);
	exit(0);
}
