/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAXARRAY_H_RPCGEN
#define _MAXARRAY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int array[100];
	int size;
};
typedef struct numbers numbers;

#define maxArray_PROG 0x4562877
#define maxArray_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define maxArray 1
extern  int * maxarray_1(numbers *, CLIENT *);
extern  int * maxarray_1_svc(numbers *, struct svc_req *);
extern int maxarray_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define maxArray 1
extern  int * maxarray_1();
extern  int * maxarray_1_svc();
extern int maxarray_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAXARRAY_H_RPCGEN */
